name: Bale Module Build

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      - self-hosted
      - summary
      - module

    steps:
      - name: Checkout Module
        uses: actions/checkout@v4
        with:
          path: D:\Summary\src\Modules\${{ github.event.repository.name }}

      - name: Build Module
        shell: powershell
        run: |
          $module = "${{ github.event.repository.name }}"

          Write-Host "Building module: $module"

          cd D:\Summary-Test\src\Modules\$module

          dotnet restore

          dotnet build --configuration Release